config/urls.py
from django.contrib import admin
from django.urls import path, include       #new
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('main.urls')),
	path('account/', include('account.urls')),
	path('order/', include('order.urls')),
	path('product/', include('product.urls')),
	path('qna/', include('qna.urls')),
	path('profit/', include('profit.urls')),
	path('revenue/', include('revenue.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profit/urls.py
from django.urls import path
from . import views

app_name = 'profit'

urlpatterns = [
	path('', views.profit_list, name='list'),
	path('export/', views.profit_export, name='export'),
	path('catalog/', views.profit_catalog, name='catalog'),
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
	path('', views.qna_list, name='list'),
	path('<int:qna_id>/', views.qna_detail, name='detail'),
]

profit/models.py
from django.db import models
from datetime import date
from django.conf import settings
from datetime import datetime
from order.models import OrderItem
# Create your models here.


class ProfitDone(models.Model):
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	total_profit_amount=models.DecimalField(max_digits=14, decimal_places=2)
	seller = models.ForeignKey(
			settings.AUTH_USER_MODEL,
			on_delete=models.CASCADE,
	)
	total_payment_fee = models.DecimalField(max_digits=14, decimal_places=2)
	profit_done_amount=models.DecimalField(max_digits=14, decimal_places=2)
	total_shipping_fee = models.DecimalField(max_digits=14, decimal_places=2)

	class Meta:
		db_table = 'ecommerce_profit_done'


class Profit(models.Model):
	order_item = models.ForeignKey(
			OrderItem,
			on_delete=models.CASCADE,
	)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
	charge_amount = models.DecimalField(max_digits=14, decimal_places=2)
	payment_fee = models.DecimalField(max_digits=14, decimal_places=2)
	profit_amount = models.DecimalField(max_digits=14, decimal_places=2)
	seller = models.ForeignKey(
			settings.AUTH_USER_MODEL,
			on_delete=models.CASCADE,
	)
	profit_done = models.ForeignKey(
			ProfitDone,
			on_delete=models.CASCADE,
			null=True
	)

	class Meta:
		db_table = 'ecommerce_profit'
	

profit/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q, Sum
from .models import *
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import json, re
import urllib
import xlwt
User = get_user_model()

def profit_list(request):
	profit_objs = Profit.objects.filter(profit_done=None)
	profit_amount = profit_objs.aggregate(Sum('profit_amount'))['profit_amount__sum']
	if profit_amount is None:
		profit_amount = 0

	now = date.today()
	start_date = now-relativedelta(months=1)
	end_date = now

	if request.GET.get("start_date") is not None and request.GET.get("start_date") != '':
		start_date = datetime.strptime(request.GET.get("start_date"), "%Y-%m-%d")

	if request.GET.get("end_date") is not None and request.GET.get("end_date") != '':
		end_date = datetime.strptime(request.GET.get("end_date"), "%Y-%m-%d")

	start_date = start_date + timedelta(days=1)
	
	profit_done_objs = ProfitDone.objects.filter(created_at__range=[start_date, end_date])

	page        = int(request.GET.get('p', 1))
	pagenator   = Paginator(profit_done_objs, 10)
	profit_done_objs = pagenator.get_page(page)

	return render(request, 'profit/profit_list.html', {
		"profit_objs": profit_objs,
		'profit_amount': profit_amount,
		'profit_done_objs': profit_done_objs
	})



@login_required(login_url="account:login")
def profit_export(request):
	profit_done_obj = get_object_or_404(ProfitDone, pk=request.GET.get("id"))
	
	q = Q()
	q &= Q(profit_done=profit_done_obj)

	profit_objs = Profit.objects.filter(q).order_by(
		'-id'
	).extra(
		select={'created_at_date': 'DATE(created_at)'}
	).values_list(
		'created_at_date', 
		'charge_amount',
		'payment_fee', 
		'profit_amount',
	)

	file_name = urllib.parse.quote(str(f"{request.user.username} 매출").encode('utf-8'))

	response = HttpResponse(content_type="application/vnd.ms-excel")
	response["Content-Disposition"] = f'attachment;filename*=UTF-8\'\'{file_name}.xls' 
	wb = xlwt.Workbook(encoding='ansi') #encoding은 ansi로 해준다.
	ws = wb.add_sheet('신청자') #시트 추가
	
	row_num = 0
	col_names = ['날짜', '금액', '수수료', '배송비']
	
	#열이름을 첫번째 행에 추가 시켜준다.
	for idx, col_name in enumerate(col_names):
		ws.write(row_num, idx, col_name)
	
	
	
	#유저정보를 한줄씩 작성한다.
	for profit_obj in profit_objs:
		row_num +=1
		for col_num, attr in enumerate(profit_obj):
			ws.write(row_num, col_num, str(attr))
					
	wb.save(response)
	
	return response

def profit_catalog(request):
	return render(request, 'profit/profit_catalog.html')

templates/profit/profit_catalog.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load util_filter %}
{% load mathfilters %}

<div class="page-content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header justify-content-between d-flex align-items-center">
						<h4 class="card-title">정산 목록 <span class="text-muted fw-normal ms-2">(34)</span></h4>
					</div>
					<div class="card-body p-3">
						<div class="text-end">
							<div class="d-flex flex-wrap align-items-start justify-content-md-end mt-2 mt-md-0 gap-2 mb-3">
								<div>
									<a href="#" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#addContactModal"><i class="uil uil-plus me-1"></i> Add New</a>
								</div>                                                    
							</div>
						</div>

						<!-- Modal -->
						<div class="modal fade" id="addContactModal" tabindex="-1" aria-labelledby="addContactModalLabel" aria-hidden="true">
							<div class="modal-dialog modal-lg modal-dialog-centered">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title" id="addContactModalLabel">Add Contact</h5>
										<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
									</div>
									<div class="modal-body p-4">
										<div>
											<div class="mb-3">
												<label for="addcontact-name-input" class="form-label">Name</label>
												<input type="text" class="form-control" id="addcontact-name-input" placeholder="Enter Name">
											</div>
											<div class="mb-3">
												<label for="addcontact-designation-input" class="form-label">Company</label>
												<input type="text" class="form-control" id="addcontact-designation-input" placeholder="Enter Company Name">
											</div>
											<div class="mb-3">
												<label for="addcontact-file-input" class="form-label">Phone Number</label>
												<input type="text" class="form-control" id="addcontact-file-input">
											</div>
											<div class="mb-3">
												<label for="addcontact-email-input" class="form-label">Email Address</label>
												<input type="email" class="form-control" id="addcontact-email-input" placeholder="Enter Email Address">
											</div>
											<div class="mb-3">
												<label for="addcontact-email-input" class="form-label">Account Number</label>
												<input type="email" class="form-control" id="addcontact-email-input" placeholder="Enter Account Number">
											</div>
										</div>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-light w-sm" data-bs-dismiss="modal">Close</button>
										<button type="button" class="btn btn-primary w-sm">Add</button>
									</div>
								</div>
							</div>
						</div>
						<!-- end modal -->

						<div class="table-responsive">
							<table class="table align-middle table-nowrap table-check">
								<thead>
									<tr>
										<th scope="col" style="width: 50px;">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" id="checkAll">
												<label class="form-check-label" for="checkAll"></label>
											</div>
										</th>
										<th scope="col" class="d-flex justify-content-between">Name
											<div class="sort-arrow d-flex align-items-center flex-column">
												<img src="{% static 'images/up-arrow.png' %}" style="width: 13px; cursor: pointer;">
												<img src="{% static 'images/down-arrow.png' %}" style="width: 13px; cursor: pointer;">
											</div>
										</th>
										<th scope="col">Company</th>
										<th scope="col">Phone</th>
										<th scope="col">Email</th>
										<th scope="col">Account</th>
										<th scope="col">Status</th>
										<th style="width: 80px; min-width: 80px;">Action</th>
									</tr><!-- end tr -->
								</thead><!-- end thead -->
								<tbody>
									<tr>
										<th scope="row">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" id="contacusercheck1">
												<label class="form-check-label" for="contacusercheck1"></label>
											</div>
										</th>
										<td class="sort-name">
											<span class="text-body fw-medium">Donald Risher</span>
										</td>
										<td>AwesomeHomcare</td>
										<td>02-8856-9210</td>
										<td>selleremail@email.com</td>
										<td>Account number here</td>
										<td>이체 대기중</td>
										<td>
											<div class="dropdown">
												<button class="btn btn-light btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
													<i class="uil uil-ellipsis-h"></i>
												</button>
												<ul class="dropdown-menu dropdown-menu-end">
													<li><a class="dropdown-item" href="#">이체 완료</a></li>
													<li><a class="dropdown-item" href="#">이체 취소</a></li>
												</ul>
											</div>
										</td>
									</tr><!-- end tr -->
									<tr>
										<th scope="row">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" id="contacusercheck1">
												<label class="form-check-label" for="contacusercheck1"></label>
											</div>
										</th>
										<td class="sort-name">
											<span class="text-body fw-medium">Aonald Risher</span>
										</td>
										<td>AwesomeHomcare</td>
										<td>02-8856-9210</td>
										<td>selleremail@email.com</td>
										<td>Account number here</td>
										<td>이체 대기중</td>
										<td>
											<div class="dropdown">
												<button class="btn btn-light btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
													<i class="uil uil-ellipsis-h"></i>
												</button>
												<ul class="dropdown-menu dropdown-menu-end">
													<li><a class="dropdown-item" href="#">이체 완료</a></li>
													<li><a class="dropdown-item" href="#">이체 취소</a></li>
												</ul>
											</div>
										</td>
									</tr><!-- end tr -->
									<tr>
										<th scope="row">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" id="contacusercheck1">
												<label class="form-check-label" for="contacusercheck1"></label>
											</div>
										</th>
										<td class="sort-name">
											<span class="text-body fw-medium">Bonald Risher</span>
										</td>
										<td>AwesomeHomcare</td>
										<td>02-8856-9210</td>
										<td>selleremail@email.com</td>
										<td>Account number here</td>
										<td>이체 대기중</td>
										<td>
											<div class="dropdown">
												<button class="btn btn-light btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
													<i class="uil uil-ellipsis-h"></i>
												</button>
												<ul class="dropdown-menu dropdown-menu-end">
													<li><a class="dropdown-item" href="#">이체 완료</a></li>
													<li><a class="dropdown-item" href="#">이체 취소</a></li>
												</ul>
											</div>
										</td>
									</tr><!-- end tr -->
									<tr>
										<th scope="row">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" id="contacusercheck1">
												<label class="form-check-label" for="contacusercheck1"></label>
											</div>
										</th>
										<td class="sort-name">
											<span class="text-body fw-medium">Conald Risher</span>
										</td>
										<td>AwesomeHomcare</td>
										<td>02-8856-9210</td>
										<td>selleremail@email.com</td>
										<td>Account number here</td>
										<td>이체 대기중</td>
										<td>
											<div class="dropdown">
												<button class="btn btn-light btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
													<i class="uil uil-ellipsis-h"></i>
												</button>
												<ul class="dropdown-menu dropdown-menu-end">
													<li><a class="dropdown-item" href="#">이체 완료</a></li>
													<li><a class="dropdown-item" href="#">이체 취소</a></li>
												</ul>
											</div>
										</td>
									</tr><!-- end tr -->
								</tbody><!-- end tbody -->
							</table><!-- end table -->
						</div><!-- end table responsive -->

						<div class="row g-0 text-center text-sm-start">
							<div class="col-sm-6">
								<div>
									<p class="mb-sm-0">Showing 1 to 10 of 57 entries</p>
								</div>
							</div>
							<!-- end col -->
							<div class="col-sm-6">
								<ul class="pagination pagination-rounded justify-content-center justify-content-sm-end mb-sm-0">
									<li class="page-item disabled">
										<a href="#" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
									</li>
									<li class="page-item">
										<a href="#" class="page-link">1</a>
									</li>
									<li class="page-item active">
										<a href="#" class="page-link">2</a>
									</li>
									<li class="page-item">
										<a href="#" class="page-link">3</a>
									</li>
									<li class="page-item">
										<a href="#" class="page-link">4</a>
									</li>
									<li class="page-item">
										<a href="#" class="page-link">5</a>
									</li>
									<li class="page-item">
										<a href="#" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
									</li>
								</ul>
							</div><!-- end col -->
						</div><!-- end row -->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
let sortName = document.querySelectorAll(".sort-name > span");
let upArrow = document.querySelector(".sort-arrow").firstElementChild;
let downArrow = document.querySelector(".sort-arrow").lastElementChild;
let arr = [];


for(var i=0; i<sortName.length; i++){
	arr.push(sortName[i].innerText);
}
upArrow.addEventListener("click", ()=>{
	let sortResult = arr.sort();	
	
	for(var i=0; i<sortName.length; i++){
		sortName[i].innerText = sortResult[i];
	}

});

</script>
{% endblock %}

templates/profit/profit_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load util_filter %}
{% load mathfilters %}

<style>
@media only screen and (max-width: 767px) {
	.btn-group {
		width: 100% !important;
		margin-bottom: 20px;
	}
}
</style>
<!-- Begin page -->
<div class="page-content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header justify-content-between d-flex align-items-center">
						<h4 class="card-title">정산 관리</h4>
					</div>
					<div class="card-body p-3">
						<div class="d-md-flex justify-content-center align-items-center mb-5">
							<div class="btn-group" id="date-btn">
								<button type="button" class="btn btn-outline-secondary" onclick="todayBtn()">오늘</button>
								<button type="button" class="btn btn-outline-secondary" onclick="setLastWeek()">1주일</button>
								<button type="button" class="btn btn-outline-secondary" onclick="setLastMonth(1)">1개월</button>
								<button type="button" class="btn btn-outline-secondary" onclick="setLastMonth(3)">3개월</button>
								<button type="button" class="btn btn-outline-secondary" onclick="setLastMonth(6)">6개월</button>
							</div>
							<form action="{{request.path}}" method="GET" name="dateSearchForm">
								<div class="d-flex align-items-center ms-md-5 ms-0">
									<input class="form-control form-radius border-secondary" name="start_date" type="date" id="start-date-input">
									&nbsp;&nbsp;~&nbsp;&nbsp;
									<input class="form-control form-radius border-secondary" name="end_date" type="date" id="end-date-input">
									<button type="submit" data-bs-target="#" data-bs-toggle="collapse" class="ms-2 border-0 bg-white">
										<i class="bx bx-search-alt-2 fs-4"></i>
									</button>
								</div>
							</form>
						</div>
						<div class="row justify-content-center">
							<div class="col-md-6">
								<div class="card pay-done">
									<div class="card-body text-center">
										<h5 class="card-title fw-bold mb-2">정산 예정 금액</h5>
										<p class="card-text" style="color: rgb(101, 202, 113); "><b class="fs-1">₱{{profit_amount|intcomma}}</b></p>
									</div>
								</div>
							</div>
						</div>
						<div class="responsiveTable">
							<table class="table mt-3 mb-0 text-center">
								<thead class="align-middle table-light">
									<tr>
										<th rowspan="2">회원</th>
										<th rowspan="2">정산일</th>
										<th rowspan="2">정산금액</th>
										<th colspan="3">상세내역</th>
										<th rowspan="2">세부내역 다운로드</th>				
									</tr>
									<tr>
										<th>상품 결제금액</th>
										<th>결제 수수료</th>
										<th>배송비</th>
									</tr>
								</thead>
								<tbody>
									{% for profit_done_obj in profit_done_objs %}
									<tr class="border-bottom">
										<td data-label="회원">{{profit_done_obj.seller.username}}</td>
										<td data-label="정산일">{{profit_done_obj.created_at}}</td>
										<td data-label="정산금액">₱{{profit_done_obj.profit_done_amount|intcomma}}</td>
										<td data-label="상품 결제금액">₱{{profit_done_obj.total_profit_amount|intcomma}}</td>
										<td data-label="결제 수수료">₱{{profit_done_obj.total_payment_fee|intcomma}}</td>
										<td data-label="배송비">₱{{profit_done_obj.total_shipping_fee|intcomma}}</td>
										<td data-label="세부내역 다운로드">
											<div class="excel-btn">
												<a href="{% url 'profit:export' %}?id={{profit_done_obj.pk}}">
													<span class="btn btn-outline-secondary"><img class="me-2" style="width: 40px;" src="{% static 'images/down_i.png' %}">Excel Download</span>
												</a>
											</div>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table><!-- end table --> 
						</div>	
						

						<div class="row g-0 text-center text-sm-start mt-3">
							<!-- end col -->
							<div class="col-12">
								<ul class="pagination pagination-rounded justify-content-center mb-sm-0">
									{% if profit_done_objs.has_previous %}
									<li class="page-item">
										<a href="?p={{profit_done_objs.previous_page_number }}" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
									</li>
									{% else %}
									<li class="page-item disabled">
										<span class="page-link"><i class="mdi mdi-chevron-left"></i></span>
									</li>
									{% endif %}
									
									{% for page_number in profit_done_objs.paginator.page_range %}
										{% if page_number >= profit_done_objs.number|add:-2 and page_number <= profit_done_objs.number|add:2 %}
											{% if page_number == profit_done_objs.number %}
											<li class="page-item active">
												<span class="page-link">{{ page_number }}</span>
											</li>
											{% else %}
											<li class="page-item">
												<a href="?p={{page_number }}" class="page-link">{{ page_number }}</a>
											</li>
											{% endif %}
										{% endif %}
									{% endfor %}
									
									{% if profit_done_objs.has_next  %}
									<li class="page-item">
										<a href="?p={{profit_done_objs.next_page_number }}" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
									</li>
									{% else %}
									<li class="page-item disabled">
										<span class="page-link"><i class="mdi mdi-chevron-right"></i></span>
									</li>
									{% endif %}
								</ul>
							</div><!-- end col -->
						</div><!-- end row -->
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>

//==============================
// URL 파라미터 날짜 시작일에 적용
//==============================

const curUrl = window.location.href;
const url = new URL(curUrl);
const urlParams = url.searchParams;

/*종료 날짜 오늘 날짜로 지정*/
document.getElementById("end-date-input").value = new Date().toISOString().slice(0,10);

/*새로 페이지 들어올 시 한달 전 날짜로 셋팅*/
if (urlParams.has('start_date') == false) {
	setLastMonth(1);
}else{
	document.getElementById("start-date-input").value = urlParams.get('start_date');
}

//==============================
// 기간별 날짜 적용
//==============================

function todayBtn(){
	document.getElementById("start-date-input").value = new Date().toISOString().slice(0,10);
	document.getElementById("end-date-input").value = new Date().toISOString().slice(0,10);
}

function setLastWeek(){
	let now = new Date();	// 현재 날짜 및 시간
	let lastweek = new Date(now.setDate(now.getDate() - 7)); // 일주일 전

	let weekYear = lastweek.getFullYear();
	let weekMonth = lastweek.getMonth() + 1;
	let weekDay = lastweek.getDate();

	if(weekMonth < 10) {weekMonth = "0" + weekMonth};
	if(weekDay < 10) {weekDay = "0" + weekDay};

	let resultDate = weekYear + "-" + weekMonth + "-" + weekDay;

  document.getElementById("start-date-input").value = resultDate;
} 

function setLastMonth(numMonthAgo){
	let now = new Date();
	let setMonthAgo = new Date(now.setMonth(now.getMonth() - numMonthAgo))
	let weekYear = setMonthAgo.getFullYear();
	let weekMonth = setMonthAgo.getMonth() + 1;
	let weekDay = setMonthAgo.getDate();

	if(weekMonth < 10) {weekMonth = "0" + weekMonth};
	if(weekDay < 10) {weekDay = "0" + weekDay};

	let resultDate = weekYear + "-" + weekMonth + "-" + weekDay;

	document.getElementById("start-date-input").value = resultDate;
}
</script>
{% endblock %}