config/urls.py
from django.contrib import admin
from django.urls import path, include       #new
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('main.urls')),
	path('account/', include('account.urls')),
	path('order/', include('order.urls')),
	path('product/', include('product.urls')),
	path('qna/', include('qna.urls')),
	path('profit/', include('profit.urls')),
	path('revenue/', include('revenue.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
	path('', views.qna_list, name='list'),
	path('<int:qna_id>/', views.qna_detail, name='detail'),
]

qna/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class QnA(models.Model):
	user = models.ForeignKey(
				settings.AUTH_USER_MODEL,
				on_delete=models.CASCADE,
	)
	qna_type = models.CharField(max_length=255)
	subject = models.CharField(max_length=255)
	question = models.TextField()
	answer = models.TextField()
	questioned_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	answered_at = models.DateTimeField(null=True)

	class Meta:
		db_table = 'ecommerce_qna'

qna/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import *
from django.core.paginator import Paginator
from django.db.models import Q
from datetime import datetime
import json
# Create your views here.

@login_required(login_url="account:login")
def qna_list(request):
	seo = {
		'title': "유토빌",
	}

	qna_objs =  QnA.objects.all().order_by('-id')
	
	page        = int(request.GET.get('p', 1))
	pagenator   = Paginator(qna_objs, 12)
	qna_objs = pagenator.get_page(page)

	return render(request, 'qna/qna_list.html',{
		"seo": seo,
		"qna_objs": qna_objs,
	})


@login_required(login_url="account:login")
def qna_detail(request, qna_id):
	seo = {
		'title': "유토빌",
	}

	try:
		qna_obj = QnA.objects.get(pk=qna_id)
	except:
		return redirect('/')

	if request.method == 'POST':
		jsonData = json.loads(request.body)
		answer = jsonData.get('answer')
				
		try:
			qna_obj.answer = answer
			qna_obj.answered_at = datetime.now()
			qna_obj.save()

			result = '200'
			result_text = "답변이 완료되었습니다."
		except:
			result = '201'
			result_text = '알수없는 오류입니다. 다시시도 해주세요.'

		return JsonResponse({
			'result': result, 
			'result_text': result_text
		})
	else:
		return render(request, 'qna/qna_detail.html',{
			"seo":seo,
			"qna_obj": qna_obj
		})

templates/qna/qna_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load util_filter %}

<!-- Begin page -->

<div class="page-content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="page-title-box d-flex align-items-center justify-content-between">
					<h4 class="mb-0">문의내용</h4>

					<div class="page-title-right">
						<ol class="breadcrumb m-0">
							<li class="breadcrumb-item"><a href="javascript: void(0);">Contacts</a></li>
							<li class="breadcrumb-item active">User List</li>
						</ol>
					</div>

				</div>
			</div>
		</div>
		<!-- end page title -->

		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						<h5 class="mt-0 mb-4 font-size-16">{{qna_obj.subject}}</h5>

						<div>
							{{qna_obj.question|safe}}
						</div>
						<hr/>
						
						<form name="qnaForm">
							{% csrf_token %}
							<div class="py-3">
								<h6>답변</h6>
								<textarea class="form-control" name="answer" placeholder="Leave a comment here" style="height: 300px">{{qna_obj.answer}}</textarea>
							</div>

							<div class="text-end">
								<a href="{% url 'qna:list' %}" class="btn btn-light mt-4">목록</a>
								<a href="#!" onclick="qna_submit();" class="btn btn-primary mt-4">답변완료</a>
							</div>
						</form>
					</div>

				</div>
			</div><!-- end col -->
		</div><!-- end row -->
	</div>
</div>


<div class="modal fade" data-bs-backdrop="static" id="qnaDeleteModal" tabindex="-1">
	<div class="modal-dialog modal-dialog-centered modal-md">
		<div class="modal-content">
			<div class="modal-header p-4">
			<h4 class="mb-0 text-center">알림</h4>
			<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>

			<div class="modal-body p-4">
				정말로 답변을 거부하시겠습니까?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline-primary ms-1" onclick="qna_delete_submit();">확인</button>
				<button type="button" class="btn btn-primary btn-md" data-bs-dismiss="modal">취소</button>
			</div>

		</div>
	</div>
</div>

<script>
var is_run = false;

	
async function qna_submit() {
	var qnaForm = document.qnaForm;
	var answer = qnaForm.answer.value;
	
	if (isEmpty(answer)) {
			openModal('알림','답변을 입력해주세요.');
		return false;
	}

	if(is_run == true) {
		openModal('알림','잠시후에 다시시도 해주세요.');
		return false;
	}

	is_run = true;
	
	const response = await fetch("{{request.path}}", {
		method: "POST",
		headers: {
			"X-CSRFToken": getCookie("csrftoken"),
		},
		body: JSON.stringify({
			'answer': answer,
		}),
	})
	.then(response => response.json())
	.then(data => {
		is_run  = false;
		if (data.result == '200') {
			openModal("알림", data.result_text, '#qnaDeleteModal', `location.href="{% url 'qna:list' %}";`);
		} else {
			openModal("알림", data.result_text, '#qnaDeleteModal');
		}
	});
}


</script>

{% endblock %}

templates/qna/qna_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load util_filter %}

<!-- Begin page -->

<div class="page-content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header justify-content-between d-flex align-items-center">
						<h4 class="card-title">문의 내역</h4>
					</div>
					<div class="card-body">				
						<div class="responsiveTable">					
							<table class="table mt-3 mb-0 text-center">
								<thead class="table-light">
									<tr>
										<th scope="col" style="width: 50px;">No.</th>
										<th scope="col">제목</th>
										<th scope="col" style="width: 100px;">상태</th>
										<th scope="col" style="width:15%;">날짜</th>
									</tr><!-- end tr -->
								</thead><!-- end thead -->
								<tbody>
									{% for qna_obj in qna_objs %}
									<tr>
										<td scope="row" data-label="No.">
											{{forloop.counter}}
										</td>

										<td data-label="제목">
											<a href="{% url 'qna:detail' qna_obj.pk %}" class="text-link fw-medium">{{qna_obj.subject}}</a>
										</td>

										<td data-label="상태">
											<span href="#" class="badge badge-soft-primary">
												{% if qna_obj.answered_at is not None %}
													답변완료
												{% else %}
													답변대기
												{% endif %}
											</span>
										</td>

										<td data-label="날짜">
											{{qna_obj.questioned_at}}
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>

						<div class="row g-0 text-center text-sm-start mt-3">
							<div class="col-12">
								<ul class="pagination pagination-rounded justify-content-center mb-sm-0">
									{% if qna_objs.has_previous %}
									<li class="page-item">
										<a href="?p={{qna_objs.previous_page_number }}" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
									</li>
									{% else %}
									<li class="page-item disabled">
										<span class="page-link"><i class="mdi mdi-chevron-left"></i></span>
									</li>
									{% endif %}
									
									{% for page_number in qna_objs.paginator.page_range %}
										{% if page_number >= qna_objs.number|add:-2 and page_number <= qna_objs.number|add:2 %}
											{% if page_number == qna_objs.number %}
											<li class="page-item active">
												<span class="page-link">{{ page_number }}</span>
											</li>
											{% else %}
											<li class="page-item">
												<a href="?p={{page_number }}" class="page-link">{{ page_number }}</a>
											</li>
											{% endif %}
										{% endif %}
									{% endfor %}
									
									{% if qna_objs.has_next  %}
									<li class="page-item">
										<a href="?p={{qna_objs.next_page_number }}" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
									</li>
									{% else %}
									<li class="page-item disabled">
										<span class="page-link"><i class="mdi mdi-chevron-right"></i></span>
									</li>
									{% endif %}
								</ul>
							</div><!-- end col -->
						</div><!-- end row -->
					</div><!-- end card body -->
				</div><!-- end card -->
			</div><!-- end col -->
		</div><!-- end row -->
	</div>
</div>
{% endblock %}