config/urls.py
from django.contrib import admin
from django.urls import path, include       #new
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('main.urls')),
	path('account/', include('account.urls')),
	path('order/', include('order.urls')),
	path('product/', include('product.urls')),
	path('qna/', include('qna.urls')),
	path('profit/', include('profit.urls')),
	path('revenue/', include('revenue.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
	path('', views.product_list, name='list'),
	path('write/', views.product_write, name='write'),
	path('<int:product_id>/', views.product_update, name='update'),
	path('delete/', views.product_delete, name='delete'),
	path('upload/image', views.product_upload_content_image, name='upload_image'),
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
	path('', views.qna_list, name='list'),
	path('<int:qna_id>/', views.qna_detail, name='detail'),
]

product/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from datetime import datetime
from category.models import *
from decimal import Decimal



class ModelDeleteManager(models.Manager):
	def get_queryset(self):
		return super(ModelDeleteManager, self).get_queryset().filter(is_deleted=False)


def upload_to(instance, filename):
	nowDate = datetime.now().strftime("%Y/%m/%d")
	return '/'.join([instance.folder, str(instance.product.id), nowDate, filename])


class Product(models.Model):
	user = models.ForeignKey(
				settings.AUTH_USER_MODEL,
				on_delete=models.CASCADE,
	)
	category_first = models.ForeignKey(
				CategoryFirst,
				on_delete=models.CASCADE,
	)
	category_second = models.ForeignKey(
				CategorySecond,
				on_delete=models.CASCADE,
	)
	category_third = models.ForeignKey(
				CategoryThird,
				on_delete=models.CASCADE,
	)
	product_name = models.CharField(max_length=255)
	content = models.TextField()
	price = models.DecimalField(max_digits=14, decimal_places=2)
	discount = models.DecimalField(max_digits=3, decimal_places=1, default=0)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
	is_deleted = models.BooleanField(default=False)
	deleted_at = models.DateTimeField(null=True)
	rating = models.DecimalField(max_digits = 2, decimal_places = 1, default=0.0)
	rating_count = models.PositiveIntegerField(default=0)
	review = models.ManyToManyField(
				settings.AUTH_USER_MODEL,
				related_name="my_review",
				blank=True,
				through='ProductReview'
	)


	objects = ModelDeleteManager()

	class Meta:
		db_table = 'ecommerce_product'

	@property
	def amount(self):
		return int(self.price)


class ProductArea(models.Model):
	product = models.ForeignKey(
			Product,
			on_delete=models.CASCADE
	)
	area = models.CharField(max_length=255)

	class Meta:
		db_table = 'ecommerce_product_area'

	def __str__(self) :
		return self.area


class ProductVariant(models.Model):
	product = models.ForeignKey(
			Product,
			on_delete=models.CASCADE
	)
	variant = models.CharField(max_length=255)
	is_deleted = models.BooleanField(default=False)
	deleted_at = models.DateTimeField(null=True)

	objects = ModelDeleteManager()

	class Meta:
		db_table = 'ecommerce_product_variant'

	def __str__(self) :
		return self.variant


class ProductVariantValue(models.Model):
	variant = models.ForeignKey(
			ProductVariant,
			on_delete=models.CASCADE
	)
	value = models.CharField(max_length=255)
	price = models.DecimalField(max_digits=14, decimal_places=2)
	is_deleted = models.BooleanField(default=False)
	deleted_at = models.DateTimeField(null=True)

	objects = ModelDeleteManager()
	
	class Meta:
		db_table = 'ecommerce_product_variant_value'



class ProductImage(models.Model):
	image = models.FileField(upload_to=upload_to)
	folder = 'ecommerce/product'
	product = models.ForeignKey(
			Product,
			on_delete=models.CASCADE
	)
	
	class Meta:
		db_table = 'ecommerce_product_image'



class ProductThumbnail(models.Model):
	product = models.ForeignKey(
			Product,
			on_delete=models.CASCADE
	)

	folder = 'ecommerce/product'
	thumbnail = ProcessedImageField(
				upload_to=upload_to,
				processors=[ResizeToFill(800, 800)],
	)

	class Meta:
		db_table = 'ecommerce_product_thumbnail'


class ProductReview(models.Model):
	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
			Product,
			on_delete=models.CASCADE
	)
	review = models.TextField()
	rating = models.PositiveIntegerField()
	created_at = models.DateTimeField(default=datetime.now)

	class Meta:
		db_table = 'ecommerce_product_review'

	def save(self, *args, **kwargs):
		try:
			self.product.rating = ((Decimal(self.product.rating) * self.product.rating_count) + Decimal(self.rating)) / (self.product.rating_count+1)
			self.product.rating_count += 1
			self.product.save()
		except:
			pass

		super().save(*args, **kwargs)


class ProductQnA(models.Model):
	product = models.ForeignKey(
			Product,
			on_delete=models.CASCADE
	)
	user = models.ForeignKey(
				settings.AUTH_USER_MODEL,
				on_delete=models.CASCADE,
	)
	question = models.TextField()
	answer = models.TextField()
	questioned_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	answered_at = models.DateTimeField(auto_now_add=False, auto_now=True)
	is_deleted = models.BooleanField(default=False)
	deleted_at = models.DateTimeField(null=True)

	objects = ModelDeleteManager()

	class Meta:
		db_table = 'ecommerce_product_qna'

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import *
from django.core.paginator import Paginator
from django.http import JsonResponse
import json, re
# Create your views here.

@login_required(login_url="account:login")
def product_list(request):
	seo = {
		'title': "상품 리스트 - 유토빌",
	}
	product_list =  Product.objects.all().order_by( "-id")
	
	page        = int(request.GET.get('p', 1))
	pagenator   = Paginator(product_list, 12)
	product_list = pagenator.get_page(page)

	return render(request, 'product/product_list.html',{
		"seo":seo,
		'product_list': product_list
	})


@login_required(login_url="account:login")
def product_write(request):
	seo = {
		'title': "체험단 모집 - 콘디",
	}

	if request.method == 'POST':
		product_name = request.POST.get('product_name')
		area = request.POST.get('area')
		price = re.sub(r'[^0-9]', '', request.POST.get('price'))
		content = request.POST.get('content')
		category_first = request.POST.get('category_first')
		category_second = request.POST.get('category_second')
		category_third = request.POST.get('category_third')
		options_data = request.POST.get('options_data')

		try:
			thumbnails = request.FILES.getlist('thumbnail')
			print(thumbnails)
		except:
			result = {'result': '201', 'result_text': '대표 이미지을 등록해주세요.'}
			return JsonResponse(result)

		if category_first is None or category_first == '':
			result = {'result': '201', 'result_text': '대분류를 선택해주세요.'}
			return JsonResponse(result)

		if category_second is None or category_second == '':
			result = {'result': '201', 'result_text': '중분류를 선택해주세요.'}
			return JsonResponse(result)
		
		try:
			category_third_obj = CategoryThird.objects.get(pk=category_third, parent__name=category_second)
		except:
			result = {'result': '201', 'result_text': '소분류를 선택해주세요.'}
			return JsonResponse(result)

		if product_name is None or product_name == '':
			result = {'result': '201', 'result_text': '제목을 입력해주세요.'}
			return JsonResponse(result)

		if area is None or area == '':
			result = {'result': '201', 'result_text': '지역을 선택해주세요.'}
			return JsonResponse(result)

		if price is None or price == '':
			result = {'result': '201', 'result_text': '가격을 입력해주세요.'}
			return JsonResponse(result)

		if content is None or content == '':
			result = {'result': '201', 'result_text': '내용을 입력해주세요.'}
			return JsonResponse(result)

		try:
			product_obj = Product()
			product_obj.user = request.user
			product_obj.category_first = category_third_obj.parent.parent
			product_obj.category_second = category_third_obj.parent
			product_obj.category_third = category_third_obj
			product_obj.product_name = product_name
			product_obj.price = price
			product_obj.content = content
			product_obj.save()

			for thumbnail in thumbnails:
				ProductThumbnail.objects.create(product=product_obj, thumbnail=thumbnail)

			if options_data:
				list_data = json.loads(options_data)
				for obj in list_data:
					for key, value in obj.items():
						prod_var_obj = ProductVariant.objects.create(product=product_obj, variant=key)
						for k, v in value.items():
							ProductVariantValue.objects.create(variant=prod_var_obj, value=k, price=v)

			result = {'result': '200', 'result_text': '등록이 완료되었습니다.'}
			return JsonResponse(result)

		except Exception as e:
			print(e)
			result = {'result': '201', 'result_text': '알수없는 오류입니다. 관리자에게 문의해주세요.'}
			return JsonResponse(result)

	else:
		l1_l2_l3_cat_data = {}
		l1_data = CategoryFirst.objects.all()
		for l1 in l1_data:
			if l1.name not in l1_l2_l3_cat_data:
				l1_l2_l3_cat_data[l1.name] = []
			l2_cats = CategorySecond.objects.filter(parent_id=l1.id)
			for l2_cat in l2_cats:
				l2_data = {}
				if l2_cat.name not in l2_data:
					l2_data[l2_cat.name] = []
				l3_cats = CategoryThird.objects.filter(parent_id=l2_cat.id)
				for l3_cat in l3_cats:
					l2_data[l2_cat.name].append({"name":l3_cat.name, "id":l3_cat.pk})
				l1_l2_l3_cat_data[l1.name].append(l2_data)
		return render(request, 'product/product_write.html', context={"cats_data": l1_l2_l3_cat_data})


@login_required(login_url="account:login")
def product_update(request, product_id):
	seo = {
		'title': "체험단 모집 - 콘디",
	}

	if request.method == 'POST':
		product_name = request.POST.get('product_name')
		area = request.POST.get('area')
		price = re.sub(r'[^0-9]', '', request.POST.get('price'))
		content = request.POST.get('content')
		category_first = request.POST.get('category_first')
		category_second = request.POST.get('category_second')
		category_third = request.POST.get('category_third')
		options_data = request.POST.get('options_data')

		try:
			thumbnails = request.FILES.getlist('thumbnail')
		except:
			result = {'result': '201', 'result_text': '대표 이미지을 등록해주세요.'}
			return JsonResponse(result)

		if category_first is None or category_first == '':
			result = {'result': '201', 'result_text': '대분류를 선택해주세요.'}
			return JsonResponse(result)

		if category_second is None or category_second == '':
			result = {'result': '201', 'result_text': '중분류를 선택해주세요.'}
			return JsonResponse(result)
		
		try:
			category_third_obj = CategoryThird.objects.get(pk=category_third, parent__name=category_second)
		except:
			result = {'result': '201', 'result_text': '소분류를 선택해주세요.'}
			return JsonResponse(result)

		if product_name is None or product_name == '':
			result = {'result': '201', 'result_text': '제목을 입력해주세요.'}
			return JsonResponse(result)

		if area is None or area == '':
			result = {'result': '201', 'result_text': '지역을 선택해주세요.'}
			return JsonResponse(result)

		if price is None or price == '':
			result = {'result': '201', 'result_text': '가격을 입력해주세요.'}
			return JsonResponse(result)

		if content is None or content == '':
			result = {'result': '201', 'result_text': '내용을 입력해주세요.'}
			return JsonResponse(result)

		try:
			product_obj = get_object_or_404(Product, pk=product_id)
			product_obj.user = request.user
			product_obj.category_first = category_third_obj.parent.parent
			product_obj.category_second = category_third_obj.parent
			product_obj.category_third = category_third_obj
			product_obj.product_name = product_name
			product_obj.price = price
			product_obj.content = content
			product_obj.save()

			for thumbnail in thumbnails:
				ProductThumbnail.objects.get_or_create(product=product_obj, thumbnail=thumbnail)

			if options_data:
				product_var_objs = ProductVariant.objects.filter(product=product_obj)
				product_var_list = product_var_objs.values_list('id', flat=True).order_by( "-id")
				product_var_objs.update(
					is_deleted=True,
					deleted_at = datetime.now()
				)
				
				ProductVariantValue.objects.filter(pk_in=product_var_list).update(
					is_deleted=True,
					deleted_at = datetime.now()
				)

				list_data = json.loads(request.POST.get('options_data'))
				for obj in list_data:
					for key, value in obj.items():
						prod_var_obj, created = ProductVariant.objects.get_or_create(product=product_obj, variant=key)
						if created:
							for k, v in value.items():
								price = re.sub(r'[^0-9.]', '',str(v))
								prod_var_val_obj, created = ProductVariantValue.objects.get_or_create(variant=prod_var_obj, value=k, price=price)
								if not created:
									prod_var_val_obj.is_deleted=False
									prod_var_val_obj.deleted_at=None
									prod_var_val_obj.save()
						else:
							prod_var_obj.is_deleted=False
							prod_var_obj.deleted_at=None
							prod_var_obj.save()
			result = {'result': '200', 'result_text': 'Update successfully!!'}
			return JsonResponse(result)

		except Exception as e:
			print(e)
			result = {'result': '201', 'result_text': '알수없는 오류입니다. 관리자에게 문의해주세요.'}
			return JsonResponse(result)

	else:
		l1_l2_l3_cat_data = {}
		l1_data = CategoryFirst.objects.all()
		for l1 in l1_data:
			if l1.name not in l1_l2_l3_cat_data:
				l1_l2_l3_cat_data[l1.name] = []
			l2_cats = CategorySecond.objects.filter(parent_id=l1.id)
			for l2_cat in l2_cats:
				l2_data = {}
				if l2_cat.name not in l2_data:
					l2_data[l2_cat.name] = []
				l3_cats = CategoryThird.objects.filter(parent_id=l2_cat.id)
				for l3_cat in l3_cats:
					l2_data[l2_cat.name].append({"name":l3_cat.name, "id":l3_cat.pk})
				l1_l2_l3_cat_data[l1.name].append(l2_data)
				
		prod_variant_data = []
		product_obj = get_object_or_404(Product, pk=product_id)
		prod_var_obj = ProductVariant.objects.filter(product_id=product_id)
		for i in prod_var_obj:
			var_dict = {}
			val_objs = ProductVariantValue.objects.filter(variant=i)
			val_dict = {}
			for val_obj in val_objs:
				val_dict[val_obj.value] = int(val_obj.price)
			var_dict[i.variant] = val_dict
			prod_variant_data.append(var_dict)
		prod_thumb = ProductThumbnail.objects.filter(product=product_obj)
		ctx_data = {"cats_data": l1_l2_l3_cat_data, "product": product_obj, "thumbnail": prod_thumb,
					"variant_val_obj": prod_variant_data,
					"cat_sec": CategorySecond.objects.filter(parent=product_obj.category_first),
					"cat_third": CategoryThird.objects.filter(parent=product_obj.category_second)}
		return render(request, 'product/product_update.html', context=ctx_data)



def product_delete(request):
	jsonData = json.loads(request.body)
	product_id = jsonData.get('cart_item_id_arr')
	print(product_id)
	

	Product.objects.filter(pk__in=product_id).update(
		is_deleted = True, 
		deleted_at = datetime.now()
	)
	
	result = '200'
	result_text = '삭제가 완료되었습니다.'

	result = {'result': result, 'result_text': result_text}
	return JsonResponse(result)


@login_required(login_url="account:login")
def product_upload_content_image(request):
	image = request.FILES['image']
			
	try:
		product_image_obj = ProductImage()
		product_image_obj.image = image
		product_image_obj.user = request.user
		product_image_obj.save()

		return JsonResponse({
			'result': '200',
			'result_text': product_image_obj.image.url
		})

	except Exception as e:
		print(e)
		return JsonResponse({
			'result': '201',

templates/product/product_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load util_filter %}
{% load mathfilters %}

<!-- Begin page -->

<div class="page-content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header justify-content-between d-flex align-items-center">
						<h4 class="card-title">상품 관리</h4>
						<div class="text-end">
							<a href="#!" onclick="remove_checked_item();" class="remove-btn btn btn-light">체크삭제</a>
							<a href="{% url 'product:write' %}" class="btn btn-primary">상품등록</a>
						</div>
					</div>
					<div class="card-body">				
						<div class="responsiveTable">
							<table class="table mt-3 mb-0 text-center">
								<thead class="table-light">
									<tr>
										<th scope="col" style="width: 50px;">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" id="checkAll">		
											</div>
										</th>
										<th scope="col">상품명</th>
										<th scope="col">옵션</th>
										<th scope="col">판매가</th>
										<th scope="col">상태</th>
										<th scope="col" style="width: 120px">수정</th>
									</tr><!-- end tr -->
								</thead><!-- end thead -->
								<tbody>
									{% if not product_list %}
									<tr>
										<td class="border-bottom-0 text-center p-5" colspan="10">주문이 없습니다.</td>
									</tr>
									{% endif%}
									
									{% for productList in product_list %}
									<tr>
										<td scope="row">
											<div class="form-check font-size-16">
												<input type="checkbox" class="form-check-input" value="{{productList.pk}}" name="product_id">
												<label class="form-check-label" for="contacusercheck1"></label>
											</div>
										</td>	
										<td data-label="상품명">
											<span class="fw-medium">{{productList.product_name}}</span>
										</td>
										<td data-label="옵션">
											123
										</td>
										<td data-label="판매가">
											123
										</td>
										<td data-label="상태">
											<span class="badge badge-soft-primary">취소</span>
										</td>
										<td data-label="수정">
											<a href="{% url 'product:update' productList.pk %}" class="btn btn-outline-primary">수정하기</a>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>

						<div class="row g-0 text-center text-sm-start mt-3">
							<div class="col-12">
								<ul class="pagination pagination-rounded justify-content-center mb-sm-0">
									{% if product_list.has_previous %}
									<li class="page-item">
										<a href="?p={{product_list.previous_page_number }}" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
									</li>
									{% else %}
									<li class="page-item disabled">
										<span class="page-link"><i class="mdi mdi-chevron-left"></i></span>
									</li>
									{% endif %}
									
									{% for page_number in product_list.paginator.page_range %}
										{% if page_number >= product_list.number|add:-2 and page_number <= product_list.number|add:2 %}
											{% if page_number == product_list.number %}
											<li class="page-item active">
												<span class="page-link">{{ page_number }}</span>
											</li>
											{% else %}
											<li class="page-item">
												<a href="?p={{page_number }}" class="page-link">{{ page_number }}</a>
											</li>
											{% endif %}
										{% endif %}
									{% endfor %}
									
									{% if product_list.has_next  %}
									<li class="page-item">
										<a href="?p={{product_list.next_page_number }}" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
									</li>
									{% else %}
									<li class="page-item disabled">
										<span class="page-link"><i class="mdi mdi-chevron-right"></i></span>
									</li>
									{% endif %}
								</ul>
							</div><!-- end col -->
						</div><!-- end row -->
					</div><!-- end card body -->
				</div><!-- end card -->
			</div><!-- end col -->
		</div><!-- end row -->
	</div>
</div>

<script>
let is_run = false;

/*체크박스 전체 선택, 전체 해제*/
let checkAll = document.getElementById("listcheckAll");
let checkOne = document.querySelectorAll(".list-check");
var count = 0;

checkAll.addEventListener("click", function(){
	if(checkAll.checked == true){
		for(var i=0; i<checkOne.length; i++){
			checkOne[i].checked = true;	
		}
	}else{
		for(var i=0; i<checkOne.length; i++){
			checkOne[i].checked = false;	
		}			
	}

});


function remove_checked_item() {
	const item_list = document.querySelectorAll("input[name=product_id][type=checkbox]:checked");

	let arr = [];

	item_list.forEach(ele => arr.push(ele.value));

	remove_product_submit(arr);
}


async function remove_product_submit(cart_item_id) {
	if(is_run == true) {
		openModal('알림','잠시후에 다시시도 해주세요.');
		return false;
	}

	is_run = true;

    const response = await fetch("{% url 'product:delete' %}", {
		method: "POST",
		headers: {
			"X-CSRFToken": getCookie("csrftoken"),
		},
		body: JSON.stringify({
			'cart_item_id_arr':cart_item_id
		}),
	})
	.then(response => response.json())
	.then(data => {
		console.log(data);
		is_run  = false;
		if (data.result == '200') {
			window.location.reload();
		} else {
			openModal("알림", data.result_text);
		}
	});

}
</script>
{% endblock %}