account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
	path('', views.account_list, name='list'),
	path('delete/', views.account_delete, name='delete'),
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	#path('join/', views.user_join, name='join'),
	#path('confirm/<str:uidb64>/<str:token>/', views.join_confirm, name="confirm"),
	#path('find/password/', views.find_passwd, name='find_passwd'),
	#path('reset/password/<str:uidb64>/<str:token>/', views.reset_passwd, name='reset_passwd'),
	#path('re/verify/email/', views.re_verify, name='re_verify'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include       #new
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('main.urls')),
	path('account/', include('account.urls')),
	path('order/', include('order.urls')),
	path('product/', include('product.urls')),
	path('qna/', include('qna.urls')),
	path('profit/', include('profit.urls')),
	path('revenue/', include('revenue.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.index, name='index'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name='list'),
]

profit/urls.py
from django.urls import path
from . import views

app_name = 'profit'

urlpatterns = [
	path('', views.profit_list, name='list'),
	path('export/', views.profit_export, name='export'),
	path('catalog/', views.profit_catalog, name='catalog'),
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
	path('', views.qna_list, name='list'),
	path('<int:qna_id>/', views.qna_detail, name='detail'),
]

templates/base.html
{% include 'header.html' %}
{% block content %}

{% endblock %}
{% include 'footer.html' %}

templates/footer.html
{% load static %}
	<footer class="footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<script>document.write(new Date().getFullYear())</script> &copy; Utoville Homecare.
				</div>
			</div>
		</div>
	</footer>
	</div>
	<!-- end main content-->

	</div>
	<!-- END layout-wrapper -->

<div class="modal fade" id="globalModal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="globalModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-md" role="document">
		<div class="modal-content">
		<div class="modal-header p-4">
			<h4 class="mb-0 text-center" id="modal_subject">알림</h4>
			<button type="button" class="btn-close" id="closeModalBtn" data-before-modal="" onclick="closeModal()" data-bs-dismiss="modal" aria-label="Close"></button>
		</div>
		<div class="modal-body p-4" id="modal_content">
		</div>
		<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-md" id="closeModalBtn" data-before-modal="" onclick="closeModal()" data-bs-dismiss="modal">확인</button>
		</div>
		</div>
	</div>
</div>

<!-- end authentication section -->


<!-- JAVASCRIPT -->
<script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/metismenujs/dist/metismenujs.min.js' %}"></script>
<script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
<script src="{% static 'libs/feather-icons/dist/feather.min.js' %}"></script>


<!-- Vector map-->
<script src="{% static 'libs/jsvectormap/dist/js/jsvectormap.min.js' %}"></script>
<script src="{% static 'libs/jsvectormap/dist/maps/world-merc.js' %}"></script>

<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

<script src="{% static 'libs/fullcalendar/main.min.js' %}"></script>
</body>
</html>

templates/header.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Utoville HouseCare Admin</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
	<meta content="Pichforest" name="author" />
	<!-- App favicon -->
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
	<link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" /> 
	<!-- Icons css -->
		<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
	<!-- App css-->
	<link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />  
	<link href="{% static 'libs/fullcalendar/main.min.css' %}" rel="stylesheet" type="text/css" />
	<!-- Custom css -->
	<link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" />
</head>

<style>
	@media only screen and (max-width: 992px) {
		.topnav {
			position: relative;
			top: 70px;			
			text-align: center;
		}
		.navbar-nav {
			display: inline-block;

		}
		.navbar-nav li {
			display: inline-block;
		}
	}
</style>

<body data-sidebar-size="lg" data-layout-mode="light">
	<div id="layout-wrapper">
		<header id="page-topbar">
			<div class="navbar-header">
				<div class="d-flex">
					<!-- LOGO -->
					<div class="navbar-brand-box">
						<a href="{% url 'main:index' %}" class="logo">
							<span class="logo-sm">
								<img src="{% static 'images/logo-dark.png' %}" alt="" height="22">
							</span>
							<span class="logo-lg">
								<img src="{% static 'images/logo-sm-dark.png' %}" alt="" height="22">
							</span>
						</a>
					</div>
				</div>
	
				<div>
					<a href="{% url 'account:logout' %}" class="btn header-item user text-start d-flex align-items-center">
						<span class="ms-2 d-none d-sm-block user-item-desc">
							<span class="user-name">로그아웃</span>
						</span>
					</a>
				</div>
			</div>
		</header>
		<!-- ========== Left Sidebar Start ========== -->
		<div class="vertical-menu">	
			<div class="navbar-brand-box">
	
				<a href="{% url 'main:index' %}" class="logo">
					<span class="logo-lg">
						<img src="{% static 'images/logo-dark.png' %}" alt="" height="22">
					</span>
					<span class="logo-sm">
						<img src="{% static 'images/logo-sm-dark.png' %}" alt="" height="22">
					</span>
				</a>
			</div>
		
			<div data-simplebar class="sidebar-menu-scroll">
				<div id="sidebar-menu">
					<ul class="metismenu list-unstyled" id="side-menu">
						<li class="menu-title" data-key="t-components">Main</li>
						<li>
							<a href="{% url 'main:index' %}">
								<i class="icon nav-icon" data-feather="monitor"></i>
								<span class="menu-item">Dashboard</span>
							</a>
						</li>

						<li class="menu-title" data-key="t-components">Account</li>
						<li>
							<a href="{% url 'account:list' %}">
								<i class="icon nav-icon" data-feather="user"></i>
								<span class="menu-item">회원</span>
							</a>
						</li>

						<li class="menu-title" data-key="t-components">QnA</li>
						<li>
							<a href="{% url 'qna:list' %}">
								<i class="icon nav-icon" data-feather="message-square"></i>
								<span class="menu-item">문의</span>
								<span class="badge rounded-pill badge-soft-secondary">5+</span>
							</a>
						</li>

						<li class="menu-title" data-key="t-components">Profit</li>
						<li>
							<a href="{% url 'profit:list' %}">
								<i class="icon nav-icon" data-feather="tag"></i>
								<span class="menu-item">정산</span>
							</a>
						</li>
						<li>
							<a href="{% url 'profit:catalog' %}">
								<i class="icon nav-icon" data-feather="tag"></i>
								<span class="menu-item">정산 목록</span>
							</a>
						</li>

						<li class="menu-title" data-key="t-components">Revenue</li>
						<li>
							<a href="{% url 'revenue:list' %}">
								<i class="icon nav-icon" data-feather="tag"></i>
								<span class="menu-item">매출</span>
							</a>
						</li>

						<li class="menu-title" data-key="t-components">Product</li>
						<li>
							<a href="{% url 'product:list' %}">
								<i class="icon nav-icon" data-feather="briefcase"></i>
								<span class="menu-item">상품</span>
							</a>
						</li>
						
						<li class="menu-title" data-key="t-components">Order</li>
						<li>
							<a href="{% url 'order:list' %}">
								<i class="icon nav-icon" data-feather="briefcase"></i>
								<span class="menu-item">주문</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<!-- ========== Responsive Top Menu Start ========== -->		
		<div class="topnav">
			<div class="container-fluid">
				<nav class="navbar navbar-light navbar-expand-lg topnav-menu">
					<div class="navbar-collapse" id="topnav-menu-content">
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="nav-link" href="{% url 'main:index' %}">
									<i class="icon nav-icon" data-feather="monitor"></i>
									<span class="menu-item">Dashboards</span>
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="{% url 'account:list' %}">
									<i class="icon nav-icon" data-feather="package"></i>
								   <span class="menu-item">회원</span>
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="{% url 'qna:list' %}">
									<i class="icon nav-icon" data-feather="message-square"></i>
									<span class="menu-item">문의</span>
									<span class="badge rounded-pill badge-soft-secondary">{{counter_new_qna}}+</span>
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="{% url 'profit:list' %}">
									<i class="icon nav-icon" data-feather="layers"></i>
									<span class="menu-item">정산</span>
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="{% url 'revenue:list' %}">
									<i class="icon nav-icon" data-feather="file"></i>
									<span class="menu-item">매출</span>
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'product:list' %}">
									<i class="icon nav-icon" data-feather="file"></i>
									<span class="menu-item">상품</span> 
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'order:list' %}">
									<i class="icon nav-icon" data-feather="briefcase"></i>
									<span class="menu-item">주문</span> 
								</a>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>



		<!-- ============================================================== -->
		<!-- Start right Content here -->
		<!-- ============================================================== -->
		<div class="main-content">